[package]
name = "ic"
version = "0.1.0"
edition.workspace = true
description = "Fast terminal image display utility for iTerm2, similar to imgcat"

[[bin]]
name = "ic"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
buildinfo.workspace = true
clap.workspace = true
image.workspace = true
notify.workspace = true
termion.workspace = true
termgfx.workspace = true
unicode-width.workspace = true

[dev-dependencies]
libc.workspace = true

[lints]
workspace = true
