use crate::cities;
use anyhow::Result;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

/// Generate docker-compose.yml, .env, and helper scripts in the output directory.
///
/// # Errors
///
/// Returns an error if directory creation or file writing fails.
pub fn generate(
    output_dir: &Path,
    city: Option<&str>,
    container_prefix: &str,
    gluetun_version: &str,
    wireguard_key: &str,
    extra_ports: &[String],
) -> Result<()> {
    fs::create_dir_all(output_dir)?;

    let gluetun_name = format!("{container_prefix}-gluetun");
    let canonical_city = city.and_then(cities::canonical_city);

    // docker-compose.yml
    write_compose(
        output_dir,
        &gluetun_name,
        gluetun_version,
        canonical_city,
        extra_ports,
    )?;

    // .env file with WireGuard key (mode 600)
    write_env(output_dir, wireguard_key)?;

    // Helper scripts
    write_script(output_dir, "start.sh", &start_script(&gluetun_name))?;
    write_script(output_dir, "stop.sh", &stop_script())?;
    write_script(output_dir, "restart.sh", &restart_script())?;
    write_script(output_dir, "logs.sh", &logs_script())?;
    write_script(output_dir, "status.sh", &status_script(&gluetun_name))?;

    // .gitignore for the .env file
    let gitignore_path = output_dir.join(".gitignore");
    if !gitignore_path.exists() {
        fs::write(&gitignore_path, ".env\n")?;
    }

    Ok(())
}

fn write_compose(
    output_dir: &Path,
    gluetun_name: &str,
    gluetun_version: &str,
    city: Option<&str>,
    extra_ports: &[String],
) -> Result<()> {
    let city_line = match city {
        Some(c) => format!("      - SERVER_CITIES={c}\n"),
        None => String::new(),
    };

    let port_lines: String = extra_ports
        .iter()
        .map(|p| format!("      - \"{p}\"\n"))
        .collect();

    let ports_section = if extra_ports.is_empty() {
        String::from(
            "    # Expose ports here for services that share this network.\n    # ports:\n    #   - \"8080:8080\"\n",
        )
    } else {
        format!("    ports:\n{port_lines}")
    };

    let compose = format!(
        r#"# Generated by vpn-tunnel — do not edit manually.
# To route a container through this VPN, add to its service:
#   network_mode: "service:{gluetun_name}"
#   depends_on:
#     {gluetun_name}:
#       condition: service_healthy

services:
  {gluetun_name}:
    image: qmcgaw/gluetun:{gluetun_version}
    container_name: {gluetun_name}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${{WIREGUARD_PRIVATE_KEY}}
      - SERVER_COUNTRIES=United States
{city_line}      - FREE_ONLY=false
      - TZ=${{TZ:-America/New_York}}
      # Kill switch — block all traffic if VPN drops
      - FIREWALL=on
      - FIREWALL_VPN_INPUT_PORTS=
      - FIREWALL_INPUT_PORTS=
      - FIREWALL_OUTBOUND_SUBNETS=
      # Port forwarding for P2P and inbound connections
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      # DNS
      - DOT=off
      - DNS_ADDRESS=1.1.1.1
      - DNS_PLAINTEXT_ADDRESS=1.1.1.1
      # MTU tuning for VPN tunnel
      - WIREGUARD_MTU=1320
{ports_section}    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - gluetun-data:/gluetun

volumes:
  gluetun-data:
"#
    );

    fs::write(output_dir.join("docker-compose.yml"), compose)?;
    Ok(())
}

fn write_env(output_dir: &Path, wireguard_key: &str) -> Result<()> {
    let env_path = output_dir.join(".env");
    fs::write(&env_path, format!("WIREGUARD_PRIVATE_KEY={wireguard_key}\n"))?;
    fs::set_permissions(&env_path, fs::Permissions::from_mode(0o600))?;
    Ok(())
}

fn write_script(output_dir: &Path, name: &str, content: &str) -> Result<()> {
    let path = output_dir.join(name);
    fs::write(&path, content)?;
    fs::set_permissions(&path, fs::Permissions::from_mode(0o755))?;
    Ok(())
}

fn start_script(gluetun_name: &str) -> String {
    format!(
        r#"#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

echo "Starting VPN tunnel..."
docker compose up -d

echo "Waiting for VPN to become healthy..."
for i in $(seq 1 30); do
    status=$(docker inspect --format '{{{{.State.Health.Status}}}}' {gluetun_name} 2>/dev/null || echo "starting")
    if [ "$status" = "healthy" ]; then
        echo "VPN is healthy!"
        VPN_IP=$(docker exec {gluetun_name} wget -qO- icanhazip.com 2>/dev/null || echo "unknown")
        echo "VPN IP: $VPN_IP"
        exit 0
    fi
    printf "."
    sleep 3
done
echo ""
echo "ERROR: VPN failed to become healthy within 90s"
echo "Check logs with: ./logs.sh"
exit 1
"#
    )
}

fn stop_script() -> String {
    r#"#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
docker compose down
echo "VPN tunnel stopped."
"#
    .to_string()
}

fn restart_script() -> String {
    r#"#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
docker compose down
./start.sh
"#
    .to_string()
}

fn logs_script() -> String {
    r#"#!/usr/bin/env bash
cd "$(dirname "$0")"
docker compose logs -f
"#
    .to_string()
}

fn status_script(gluetun_name: &str) -> String {
    format!(
        r#"#!/usr/bin/env bash
cd "$(dirname "$0")"

echo "=== Container Status ==="
docker compose ps
echo ""

echo "=== VPN Connection ==="
VPN_IP=$(docker exec {gluetun_name} wget -qO- icanhazip.com 2>/dev/null || echo "not running")
echo "VPN IP: $VPN_IP"
"#
    )
}
