# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint

# MD007 - Unordered list indentation
# The tools list in README.md uses 4-space indentation for nested items,
# which is consistent throughout the file. Allow this existing style.
MD007:
  indent: 4

# MD013 - Line length
# Disable line length check as many tools have long descriptions
MD013: false
