// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventType } from "./EventType";

/**
 * A single event in a recording (output or input).
 */
export type Event = { time: number, type: EventType, data: string, };
