// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportFormat } from "./ExportFormat";

/**
 * Options for exporting a recording.
 */
export type ExportOptions = { input_path: string, output_path: string, format: ExportFormat, theme: string | null, compress: boolean | null, fps: number | null, resolution: string | null, optimize_web: boolean | null, };
