// TypeScript bindings generated by ts-rs.
// Run `cargo test -p nle` to regenerate.

export interface Recording {
  version: number;
  width: number;
  height: number;
  timestamp: number;
  duration: number;
  command: string;
  title: string;
  env: Record<string, string>;
  events: Event[];
}

export interface Event {
  time: number;
  type: EventType;
  data: string;
}

export type EventType = "o" | "i";

export interface ExportOptions {
  input_path: string;
  output_path: string;
  format: ExportFormat;
  theme: string | null;
  compress: boolean | null;
  fps: number | null;
  resolution: string | null;
  optimize_web: boolean | null;
}

export type ExportFormat = "Video" | "Web";

export interface LoadedRecording {
  recording: Recording;
  metadata: RecordingMetadata;
}

export interface RecordingMetadata {
  file_path: string;
  title: string;
  command: string;
  duration: number;
  event_count: number;
  width: number;
  height: number;
  timestamp: number;
}
