// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Recording } from "./Recording";
import type { RecordingMetadata } from "./RecordingMetadata";

/**
 * Response from loading a recording, includes both data and metadata.
 */
export type LoadedRecording = { recording: Recording, metadata: RecordingMetadata, };
