[package]
name = "cwt"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "cwt"
path = "src/main.rs"

[dependencies]
buildinfo.workspace = true
clap.workspace = true
colored.workspace = true
repowalker.workspace = true
shellsetup.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
