//! Enumerating and evaluating every order the branches could land in.

use crate::metrics::BranchName;

/// Every order the branches could land in, input order first.
///
/// Generated by repeatedly taking each remaining branch in its original
/// position, which yields the input order first. That matters for tie-breaking:
/// `rank` sorts stably, so an ordering that costs the same as the one the user
/// already had in mind will not be shuffled away from it.
#[must_use]
pub fn permutations(branches: &[BranchName]) -> Vec<Vec<BranchName>> {
    if branches.is_empty() {
        return vec![Vec::new()];
    }

    let mut orderings = Vec::new();

    for (index, branch) in branches.iter().enumerate() {
        let mut remaining = branches.to_vec();
        let head = remaining.remove(index);
        debug_assert_eq!(&head, branch);

        for mut tail in permutations(&remaining) {
            let mut ordering = Vec::with_capacity(branches.len());
            ordering.push(head.clone());
            ordering.append(&mut tail);
            orderings.push(ordering);
        }
    }

    orderings
}

#[cfg(test)]
mod tests {
    use super::permutations;
    use crate::metrics::BranchName;
    use std::collections::HashSet;

    fn branches(names: &[&str]) -> Vec<BranchName> {
        names.iter().map(|n| BranchName::new(*n)).collect()
    }

    #[test]
    fn enumerates_every_ordering_exactly_once_starting_with_the_input_order() {
        let input = branches(&["a", "b", "c"]);

        let orderings = permutations(&input);

        assert_eq!(
            orderings.first(),
            Some(&input),
            "the order the user typed should be evaluated first so ties favour it"
        );
        assert_eq!(orderings.len(), 6);
        let distinct: HashSet<_> = orderings.iter().collect();
        assert_eq!(distinct.len(), 6, "orderings must not repeat");
    }
}
