//! Enumerating and evaluating every order the branches could land in.

use gitscratch::BranchName;

/// How many orders `branches` branches could land in - `branches!` - or `None`
/// when that many orderings cannot be counted at all.
///
/// The count grows factorially, so it leaves `usize` behind at 21 branches on a
/// 64-bit target. Every caller goes through here, including the code that exists
/// to *reject* an oversized branch list: computing the count with a plain
/// product means the friendly refusal is itself what panics in a debug build and
/// silently wraps to nonsense in release.
#[must_use]
pub fn ordering_count(branches: usize) -> Option<usize> {
    (1..=branches).try_fold(1_usize, |total, factor| total.checked_mul(factor))
}

/// Every order the branches could land in, input order first.
///
/// Generated by repeatedly taking each remaining branch in its original
/// position, which yields the input order first. That matters for tie-breaking:
/// `rank` sorts stably, so an ordering that costs the same as the one the user
/// already had in mind will not be shuffled away from it.
#[must_use]
pub fn permutations(branches: &[BranchName]) -> Vec<Vec<BranchName>> {
    if branches.is_empty() {
        return vec![Vec::new()];
    }

    let mut orderings = Vec::new();

    for (index, branch) in branches.iter().enumerate() {
        let mut remaining = branches.to_vec();
        let head = remaining.remove(index);
        debug_assert_eq!(&head, branch);

        for mut tail in permutations(&remaining) {
            let mut ordering = Vec::with_capacity(branches.len());
            ordering.push(head.clone());
            ordering.append(&mut tail);
            orderings.push(ordering);
        }
    }

    orderings
}

#[cfg(test)]
mod tests {
    use super::{ordering_count, permutations};
    use gitscratch::BranchName;
    use std::collections::HashSet;

    fn branches(names: &[&str]) -> Vec<BranchName> {
        names.iter().map(|n| BranchName::new(*n)).collect()
    }

    #[test]
    fn enumerates_every_ordering_exactly_once_starting_with_the_input_order() {
        let input = branches(&["a", "b", "c"]);

        let orderings = permutations(&input);

        assert_eq!(
            orderings.first(),
            Some(&input),
            "the order the user typed should be evaluated first so ties favour it"
        );
        assert_eq!(orderings.len(), 6);
        let distinct: HashSet<_> = orderings.iter().collect();
        assert_eq!(distinct.len(), 6, "orderings must not repeat");
    }

    /// The count has to report "too many to count" rather than overflow, since
    /// the caller asking is usually about to refuse the run for being too big.
    #[test]
    fn counts_orderings_until_the_factorial_no_longer_fits() {
        assert_eq!(ordering_count(0), Some(1));
        assert_eq!(ordering_count(3), Some(6));
        assert_eq!(ordering_count(6), Some(720));
        assert_eq!(
            ordering_count(25),
            None,
            "25! is far past usize, so there is no honest count to report"
        );
    }
}
