[package]
name = "workit"
version = "0.1.0"
edition.workspace = true
description = "Find every Cargo.toml under a directory and write a workspace manifest that lists them as members"

[dependencies]
anyhow.workspace = true
buildinfo.workspace = true
clap.workspace = true
toml_edit.workspace = true
walkdir.workspace = true

[dev-dependencies]
regex.workspace = true

[lints]
workspace = true
