// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";

/**
 * A terminal recording, compatible with the beta recorder format.
 */
export type Recording = { version: number, width: number, height: number, timestamp: number, duration: number, command: string, title: string, env: { [key in string]?: string }, events: Array<Event>, };
