// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary metadata about a loaded recording.
 */
export type RecordingMetadata = { file_path: string, title: string, command: string, duration: number, event_count: number, width: number, height: number, timestamp: number, };
